[package]
name = "osfmk-core"
version = "0.1.0"
edition = "2021"

[features]
default = []

load_balance = [ "multi_core" ]
mmu = []
multi_core = []
multi_thread = []
numa = []
preemptive = []

[dependencies]
